
package servicebehavior;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.CSWorkerList;
import com.microsoft.schemas._2003._10.serialization.arrays.CSResultNumList;
import sutd.edu.sg.CrowdOptimizationResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrowdService", targetNamespace = "sg.edu.sutd")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    sutd.edu.sg.ObjectFactory.class
})
public interface CrowdService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "sg.edu.sutd/CrowdService/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "sg.edu.sutd")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetData", action = "sg.edu.sutd/CrowdService/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "sg.edu.sutd")
    @RequestWrapper(localName = "GetData", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GetDataResponse")
    public String getData(
        @WebParam(name = "value", targetNamespace = "sg.edu.sutd")
        Integer value);

    /**
     * 
     * @param globalCostConstraint
     * @param xml
     * @param globalTimeConstraint
     * @param workers
     * @param resultNums
     * @param numOfGeneration
     * @return
     *     returns sutd.edu.sg.CrowdOptimizationResult
     */
    @WebMethod(operationName = "GlobalOptimize", action = "sg.edu.sutd/CrowdService/GlobalOptimize")
    @WebResult(name = "GlobalOptimizeResult", targetNamespace = "sg.edu.sutd")
    @RequestWrapper(localName = "GlobalOptimize", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GlobalOptimize")
    @ResponseWrapper(localName = "GlobalOptimizeResponse", targetNamespace = "sg.edu.sutd", className = "sutd.edu.sg.GlobalOptimizeResponse")
    public CrowdOptimizationResult globalOptimize(
        @WebParam(name = "xml", targetNamespace = "sg.edu.sutd")
        String xml,
        @WebParam(name = "globalTimeConstraint", targetNamespace = "sg.edu.sutd")
        Long globalTimeConstraint,
        @WebParam(name = "globalCostConstraint", targetNamespace = "sg.edu.sutd")
        Double globalCostConstraint,
        @WebParam(name = "workers", targetNamespace = "sg.edu.sutd")
        CSWorkerList workers,
        @WebParam(name = "resultNums", targetNamespace = "sg.edu.sutd")
        CSResultNumList resultNums,
        @WebParam(name = "numOfGeneration", targetNamespace = "sg.edu.sutd")
        Integer numOfGeneration);

}
