
package servicebehavior;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrowdServiceImplement", targetNamespace = "ServiceBehavior", wsdlLocation = "http://10.131.252.225:8732/WebServiceLibrary.CrowdService.svc?wsdl")
public class CrowdServiceImplement
    extends Service
{

    private final static URL CROWDSERVICEIMPLEMENT_WSDL_LOCATION;
    private final static WebServiceException CROWDSERVICEIMPLEMENT_EXCEPTION;
    private final static QName CROWDSERVICEIMPLEMENT_QNAME = new QName("ServiceBehavior", "CrowdServiceImplement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.131.252.225:8732/WebServiceLibrary.CrowdService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CROWDSERVICEIMPLEMENT_WSDL_LOCATION = url;
        CROWDSERVICEIMPLEMENT_EXCEPTION = e;
    }

    public CrowdServiceImplement() {
        super(__getWsdlLocation(), CROWDSERVICEIMPLEMENT_QNAME);
    }

    public CrowdServiceImplement(WebServiceFeature... features) {
        super(__getWsdlLocation(), CROWDSERVICEIMPLEMENT_QNAME, features);
    }

    public CrowdServiceImplement(URL wsdlLocation) {
        super(wsdlLocation, CROWDSERVICEIMPLEMENT_QNAME);
    }

    public CrowdServiceImplement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CROWDSERVICEIMPLEMENT_QNAME, features);
    }

    public CrowdServiceImplement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrowdServiceImplement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrowdService
     */
    @WebEndpoint(name = "BasicHttpBinding_CrowdService")
    public CrowdService getBasicHttpBindingCrowdService() {
        return super.getPort(new QName("ServiceBehavior", "BasicHttpBinding_CrowdService"), CrowdService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrowdService
     */
    @WebEndpoint(name = "BasicHttpBinding_CrowdService")
    public CrowdService getBasicHttpBindingCrowdService(WebServiceFeature... features) {
        return super.getPort(new QName("ServiceBehavior", "BasicHttpBinding_CrowdService"), CrowdService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CROWDSERVICEIMPLEMENT_EXCEPTION!= null) {
            throw CROWDSERVICEIMPLEMENT_EXCEPTION;
        }
        return CROWDSERVICEIMPLEMENT_WSDL_LOCATION;
    }

}
